//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int usrid { get; set; }
        public string usrcedula { get; set; }
        public string usrapellidop { get; set; }
        public string usrapellidom { get; set; }
        public string usrnombrec { get; set; }
        public string usrmail { get; set; }
        public string usridusuario { get; set; }
        public string usrclave { get; set; }
    }
}
